# -*- coding: utf-8 -*-
"""Laptop Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_v8JUFaiV9SQmMB_aQBiqaLHPWirWc7h
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

dfC = pd.read_excel("laptopPrice.xlsx")

df = dfC.copy()

df.head(3)

df.tail(3)

df.info()

df.shape

df.describe().T

df.isnull().sum()

plt.figure(figsize=(17,6))
plt.subplot(1,3,1)
sns.barplot(x= "brand", y = "Price", data = df, color = "red")
plt.title("Price Distribution by Brand")
plt.xlabel("Brand")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.subplot(1,3,2)
sns.barplot(x= "processor_brand", y = "Price", data = df, color = "green")
plt.title("Price Breakdown by Processor Brand")
plt.xlabel("Processor Brand")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.subplot(1,3,3)
sns.barplot(x= "ram_gb", y= "Price", data = df, color = "pink")
plt.title("Price Breakdown by Ram Quantity")
plt.xlabel("Ram")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.tight_layout()
plt.show()

plt.figure(figsize = (17,6))
sns.lineplot(x= "os", y = "Price", data = df, color = "red", ci= None)
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize= (17,6))
sns.violinplot(x= "ram_gb", y = "Price", data = df, palette="Set2")
plt.tight_layout()
plt.show()

plt.figure(figsize= (17,6))
sns.barplot(x= "processor_gnrtn", y = "Price", data = df, color = "green")
plt.title("Price Breakdown by Processor", color = "red", fontweight = 15)
plt.xlabel("Processor")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.tight_layout()
plt.show()

plt.figure(figsize= (17,6))
plt.subplot(1,4,1)
sns.boxplot(x = "brand", y= "Price", data = df, palette="Set1")
plt.xlabel("Brand")
plt.ylabel("Price")
plt.xticks(rotation =50)

plt.subplot(1,4,2)
sns.boxplot(x = "processor_brand", y = "Price", data = df, palette = "Set1")
plt.xlabel("Processor Brand")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.subplot(1,4,3)
sns.boxplot(x = "ram_gb", y = "Price", data = df, palette= "Set1")
plt.xlabel("Ram GB")
plt.ylabel("Price")
plt.xticks(rotation = 50)

plt.subplot(1,4,4)
sns.boxplot(x = "os", y= "Price", data = df, palette= "Set1")
plt.xlabel("OS")
plt.ylabel("Price")
plt.xticks(rotation= 50)

plt.tight_layout()
plt.show()

